Bibabook/Bibabook/Controllers/AppEventsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bibabook.Implementation.DatabaseContext;
using Bibabook.Implementation.Models;
using Contract;
using Ninject;
using Bibabook.DAL;
using Bibabook.Filters;
using Bibabook.Models;
using Bibabook.Models.ViewModels;

namespace Bibabook.Contollers
{
    [LoggedFilter]
    public class AppEventsController : Controller
    {
        private DataBaseContext db = new DataBaseContext();
        IAppEventService eventsService;
        IKernel container = Container.Configuration.CONTAINER;

        public AppEventsController()
        {
            eventsService = container.Get<IAppEventService>();
        }

        // GET: AppEvents
        public ActionResult Index()
        {
            var events = db.AppEvents.ToList();
            return RedirectToAction("Index", "Home", events);
        }
        // GET: AppEvents/Details/5
        public async Task<ActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppEvent appEvent = await db.AppEvents.Include(x => x.Host).Include(x=>x.Guests).FirstOrDefaultAsync(x => x.AppEventID == id);
            if (appEvent == null)
            {
                return HttpNotFound();
            }
            return View(appEvent);
        }
        public ActionResult Details2(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppEvent appEvent = db.AppEvents.Include(x => x.Host).Include(x => x.Guests).FirstOrDefault(x => x.AppEventID == id);
            if (appEvent == null)
            {
                return HttpNotFound();
            }
            return View("Details",appEvent);
        }

        // GET: AppEvents/Create
        public ActionResult Create()
        {
            return View("Create");
        }

        
        // POST: AppEvents/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EventCreateViewModel model)
        {
            AppEvent appEvent = new AppEvent
            {
                AppEventID = Guid.NewGuid(),
                Name = model.Name,
                Description = model.Description,
                AdultsOnly = model.AdultsOnly,
                TimeStart = model.TimeStart,
                TimeEnd = model.TimeEnd,
                EntryFee = model.EntryFee,
                IsActive = true,
                Background = model.Background,
                Host = UserHelper.GetLogged(Session)
            };
            eventsService.Create(appEvent);

            return View("Details", appEvent);
        }

        public ActionResult Search(string name)
        {
            var events = db.AppEvents.Where(x => x.Name.Contains(name) || x.Description.Contains(name)).ToList();
            return View("List", events);
        }

        public ActionResult JoinParty([Bind(Include="partyId")]Guid partyId)
        {
            var logged = UserHelper.GetLogged(Session);
            var party = db.AppEvents.Single(x=>x.AppEventID==partyId);
            eventsService.EnrollUser(party, logged);
            return RedirectToAction("Details", new {@id= party.AppEventID });
        }

        public ActionResult LeaveParty([Bind(Include = "partyId")]Guid partyId)
        {
            
            var logged = UserHelper.GetLogged(Session);
            var party = db.AppEvents.Single(x => x.AppEventID == partyId);
            eventsService.RemoveUser(party, logged);
            
             return Redirect(Request.UrlReferrer.AbsolutePath);
            
            //return RedirectToAction("Details", new { @id = party.AppEventID });
        }

        // GET: AppEvents/Edit/5
        [HostFilter]
        public async Task<ActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppEvent appEvent = await db.AppEvents.FindAsync(id);
            if (appEvent == null)
            {
                return HttpNotFound();
            }
            return View(appEvent);
        }

        // POST: AppEvents/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [HostFilter]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "AppEventID,Name,Description,AdultsOnly,TimeStart,TimeEnd,EntryFee,IsActive,Privacy,Background,EntityID,Created,Modified,Deleted")] AppEvent appEvent)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appEvent).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            return RedirectToAction("Details",appEvent);
        }
        [HostFilter]
        // GET: AppEvents/Delete/5
        public async Task<ActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            }
            var logged = UserHelper.GetLogged(Session);
            AppEvent appEvent = db.AppEvents.Single(evt => evt.AppEventID == id);
            appEvent.IsActive = false;
            db.Entry(appEvent).State = EntityState.Modified;
            db.SaveChanges();
          
            //if (appEvent == null)
            //{
            //    return HttpNotFound();
            //}
            return RedirectToAction("Index", "Home");
        }

        // POST: AppEvents/Delete/5
        [HostFilter]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(Guid id)
        {
            AppEvent appEvent = await db.AppEvents.FindAsync(id);
            db.AppEvents.Remove(appEvent);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bibabook/Bibabook/Controllers/AppUsersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Bibabook.Implementation.DatabaseContext;
using Bibabook.Implementation.Models;
using Contract;
using Ninject;
using Bibabook.DAL;
using Bibabook.Filters;
using Bibabook.Models.ViewModels;
using Bibabook.Models;

namespace Bibabook.Controllers
{
    
    public class AppUsersController : Controller
    {
        private DataBaseContext db = new DataBaseContext();

        IAppUserService _usersService;
        IAppUserSocialService _socialService;
        IKernel container = Container.Configuration.CONTAINER;

        public AppUsersController()
        {
            _usersService = container.Get<IAppUserService>();
            _socialService = container.Get<IAppUserSocialService>();
        }

        // GET: AppUsers
        [LoggedFilter]
        public ActionResult Index()
        {
            var logged = UserHelper.GetLogged(Session);
            return View(db.AppUsers.Where(x => x.Email != logged.Email).ToList());
        }

        // GET: AppUsers - friends
        [LoggedFilter]
        public ActionResult MyFriends()
        {
            var loggedId = UserHelper.GetLogged(Session).AppUserID;
            return View("List", db.AppUsers.Single(x => x.AppUserID == loggedId).Friends.ToList());
        }

        public ActionResult Unauthorized()
        {
            return View("403");
        }

        // GET: AppUsers/Details/5
        [LoggedFilter]
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = db.AppUsers.Include(x => x.Events).Single(x => x.AppUserID == id);
            if (appUser == null)
            {
                return HttpNotFound();
            }

            AppUser activeUser = UserHelper.GetLogged(Session);
            ViewBag.IsSelf = appUser.AppUserID == activeUser.AppUserID;
            ViewBag.IsFriend = activeUser.Friends.Any(t => t.AppUserID == appUser.AppUserID);
            var eventsPart = db.AppEvents.Where(x=>x.Guests.Select(m=>m.AppUserID).Contains(appUser.AppUserID)).ToList();
            var profileViewModel = new ProfileViewModel() { AppUser = appUser, EventsParticipating = eventsPart };
            return View("Profile", profileViewModel);
        }

        // GET: AppUsers/Create
        public ActionResult Register()
        {
            return View("Register");
        }

        // POST: AppUsers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterViewModel model)
        {
            AppUser user = new AppUser
            {
                AppUserID = Guid.NewGuid(), Name = model.Name, Surname = model.Surname, 
                Email = model.Email, Birthday = model.Birthday, Sex = model.Sex, Hash = model.Password
            };
            _usersService.CreateAccount(user);
            Session[UserHelper.USER_SESSION_KEY] = user.Email;

            return RedirectToAction("Index", "Home");
        }

        

        [LoggedFilter]
        public ActionResult AddFriend(string id)
        {
            var g = new Guid(id);
            var friend = db.AppUsers.Include(x=>x.Friends).SingleOrDefault(x => x.AppUserID == g);
            if (friend != null)
            {
                _socialService.FriendUsers(UserHelper.GetLogged(Session), friend);
            }
            return View("List", UserHelper.GetLogged(Session).Friends);
        }

        [LoggedFilter]
        public ActionResult RemoveFriend(string id)
        {
            var g = new Guid(id);
            var friend = db.AppUsers.Include(x => x.Friends).SingleOrDefault(x => x.AppUserID == g);
            if (friend != null)
            {
                _socialService.UnfriendUsers(UserHelper.GetLogged(Session), friend);
            }
            return View("List", UserHelper.GetLogged(Session).Friends);
        }

        public ActionResult Login()
        {
            return View("Login");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginViewModel model)
        {
            var logged = _usersService.Login(model.Email, model.Password);
            if(logged)
            {
                Session[UserHelper.USER_SESSION_KEY] = model.Email;
            }
            return RedirectToAction("Index", "Home");
        }

        [LoggedFilter]
        public ActionResult LogOut()
        {
            Session[UserHelper.USER_SESSION_KEY] = null;
            return RedirectToAction("Index", "Home");
        }

        // GET: AppUsers/Edit/5
        [LoggedFilter]
        public ActionResult Edit(Guid? id)
        {
            if (id == null || id != UserHelper.GetLogged(Session).AppUserID)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AppUser appUser = db.AppUsers.Find(id);
            if (appUser == null)
            {
                return HttpNotFound();
            }

            EditProfileViewModel model = new EditProfileViewModel
            {
                AppUserID = appUser.AppUserID,
                Name = appUser.Name,
                Surname = appUser.Surname,
                Birthday = appUser.Birthday,
                Sex = appUser.Sex
            };

            return View("EditProfile", model);
        }

        // POST: AppUsers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [LoggedFilter]
        public ActionResult Edit(EditProfileViewModel model)
        {
            AppUser appUser = db.AppUsers.Find(model.AppUserID);
            if (appUser != null)
            {
                appUser.Name = model.Name;
                appUser.Surname = model.Surname;
                appUser.Sex = model.Sex;
                appUser.Birthday = model.Birthday;
                db.Entry(appUser).State = EntityState.Modified;
                db.SaveChanges();
                ViewBag.IsSelf = true;
                ViewBag.IsFriend = false;
                return View("Profile", appUser);
            }

            return View("EditProfile", model);
        }

        //// GET: AppUsers/Delete/5
        //[LoggedFilter]
        //public ActionResult Delete(Guid? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    AppUser appUser = db.AppUsers.Find(id);
        //    if (appUser == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(appUser);
        //}

        //// POST: AppUsers/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //[LoggedFilter]
        //public ActionResult DeleteConfirmed(Guid id)
        //{
        //    AppUser appUser = db.AppUsers.Find(id);
        //    db.AppUsers.Remove(appUser);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Bibabook/Bibabook/Views/Shared/_Header.cshtml
@{
    AjaxOptions options = new AjaxOptions
    {
        UpdateTargetId = "main-content",
        InsertionMode = InsertionMode.Replace,
    };
}

@*
     <header>

            <!-- A menu bar. -->
            <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            @Html.ActionLink("Bibabook", "Index", "Home", null, htmlAttributes: new { @class = "logo" })

            <!-- SearchBox -->
            <nav class="search-box right">
                @using (Ajax.BeginForm("Search", "Search", options))
                {
                    <div>
                        <div style="width: 280px; float: left; padding: 12px 0 14px;">
                            @Html.TextBox("name", "", new { @class = "form-control" })
                        </div>
                        <button class="btn btn-default" style="width: 100px; margin: 12px 6px 14px;" type="submit">Szukaj</button>
                    </div>
                }
            </nav>
            <!-- End: SearchBox -->
            <!--
                Miejsce na linki dostępne dla wszystkich użytkowników (gości).
                Tylko czy na dobrą sprawę czy jest jakikolwiek, który faktycznie
                powinien zostać tutaj dodany?
            -->
            @Html.Partial("_UserPanel")
        </div>
    </nav>
    </header>

*@

        <header>

            <!-- A menu bar. -->
            <nav class="navbar navbar-default navbar-fixed-top">
                <div class="container-fluid">
                    <!--float-left-->
                    <div class="navbar-header ">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        @Html.ActionLink("Bibabook", "Index", "Home", null, htmlAttributes: new { @class = "logo" })
                    </div>

                    <nav>
                        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                            <nav class="search-box pull-left">
                                @using (Ajax.BeginForm("Search", "Search", options))
                                {
                                    <div>
                                        <div style="width: 10vw; min-width: 150px; float: left; padding: 12px 0 14px;">
                                            @Html.TextBox("name", "", new { @class = "form-control" })
                                        </div>
                                        <button class="btn btn-default" style="width: 100px; margin: 12px 6px 14px;" type="submit">Szukaj</button>
                                    </div>
                                }
                            </nav>

                           @Html.Partial("_UserPanel")
                        </div>
                    </nav>
                </div>
            </nav>
        </header>

Bibabook/Bibabook/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <link href='http://fonts.googleapis.com/css?family=Monda' rel='stylesheet' type='text/css'>
    <script type="text/javascript">
        var appInsights=window.appInsights||function(config){
            function s(config){t[config]=function(){var i=arguments;t.queue.push(function(){t[config].apply(t,i)})}}var t={config:config},r=document,f=window,e="script",o=r.createElement(e),i,u;for(o.src=config.url||"//az416426.vo.msecnd.net/scripts/a/ai.0.js",r.getElementsByTagName(e)[0].parentNode.appendChild(o),t.cookie=r.cookie,t.queue=[],i=["Event","Exception","Metric","PageView","Trace"];i.length;)s("track"+i.pop());return config.disableExceptionTracking||(i="onerror",s("_"+i),u=f[i],f[i]=function(config,r,f,e,o){var s=u&&u(config,r,f,e,o);return s!==!0&&t["_"+i](config,r,f,e,o),s}),t
        }({
            instrumentationKey:"ab164bdb-02de-44f6-989c-b88e132c9b83"
        });
        
        window.appInsights=appInsights;
        appInsights.trackPageView();
    </script>
</head>
<body>
    @Html.Partial("_Header")
    @*<div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>*@
    <div class="container body-content">
        <div id="main-content"></div>
             @RenderBody()
        <hr />
        <footer class="bg-gray">
            <p>&copy; @DateTime.Now.Year - Bibabook, Informatyka SGGW 2012-2016, grupa ISI2: Adam Kostusiak, Aleksandra Ostaszewska, Damian Roguski, Filip Oraczewski, Grzegorz Podbielski, Hubert Pietruczuk, Kamil Kupiński, Karolina Wakulak, Maciej Trznadel, Mateusz Chodkowski, Mateusz Dąbrowski, Mateusz Pawlak, Piotr Breivik Szymaniak, Przemek Niedziela, Jakub Szymczuk, Wojtek Ślawski, Ignacy Wilczynski</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Bibabook/Bibabook/Views/Shared/_Today.cshtml
@model IEnumerable<Bibabook.Implementation.Models.AppEvent>
<div class="col-lg-4">
    <div class="row text-center">
        <h1 class="shadowed">Dzisiaj</h1>
    </div>
    
        <div class="container">
            @foreach (var item in Model.Where(x => x.TimeStart.Date == DateTime.Today))
            {
                if (item.IsActive)
                {
                    <div class="row center-block text-center wiersz bg-gray">
                        <img class="img-rounded" src="~/Content/UserIcon/Event.png" style="width: 150px;">
                        <h4>@item.Name</h4>

                        <div class="btn-group img-responsive">
                            @Html.ActionLink("Dołącz", "JoinParty", "AppEvents", new {@partyId = item.AppEventID}, new {@class = "btn btn-primary text-center"})

                            <a href="@Url.Action("Details", "AppEvents", new {@id = item.AppEventID})" class="btn btn-info">Zobacz wiecej!</a>
                        </div>
                    </div>
                    <hr/>
                }
            }

            </div>
</div>

Bibabook/Bibabook/Views/Shared/_UserPanel.cshtml
@using Bibabook.DAL
@using Bibabook.Implementation.Models

@{
    AppUser user = null;
    
    try
    {
        user = UserHelper.GetLogged(Session);

    }
    catch (Exception)
    {
        
    }
}

<ul class="nav navbar-nav" id="operations">

   @if (user == null)
   {

    <li>@Html.ActionLink("Zarejestruj", "Register", "AppUsers", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
    <li>@Html.ActionLink("Zaloguj się", "Login", "AppUsers", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>

   }
   else
   {

    @*<li>@Html.ActionLink("Wszystkie wydarzenia", "Index", "AppEvents")</li>*@
    <li>@Html.ActionLink("Dodaj wydarzenie", "Create", "AppEvents")</li>
    <li>@Html.ActionLink("Znajomi", "MyFriends", "AppUsers")</li>
    <li>@Html.ActionLink("Twoje dane", "Details", "AppUsers", new { id = user.AppUserID }, null)</li>
    <li>@Html.ActionLink("Wyloguj się", "LogOut", "AppUsers")</li>
    @*<li>Witaj @user.Name</li>*@

        <!--<img src="Images/portret.png" class="img-responsive" style="height:40px;" alt="Profile picture">-->

   }
</ul>
<!--
<nav class="user-panel">
    @if (user == null)
    {
        
            <li>@Html.ActionLink("Zarejestruj", "Register", "AppUsers", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
            <li>@Html.ActionLink("Zaloguj się", "Login", "AppUsers", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
        
    }
    else
    {
        
            @*<li>@Html.ActionLink("Wszystkie wydarzenia", "Index", "AppEvents")</li>*@
            <li>@Html.ActionLink("Dodaj wydarzenie", "Create", "AppEvents")</li>
            <li>@Html.ActionLink("Znajomi", "MyFriends", "AppUsers")</li>
            <li>@Html.ActionLink("Twoje dane", "Details", "AppUsers", new { id = user.AppUserID }, null)</li>
            <li>@Html.ActionLink("Wyloguj się", "LogOut", "AppUsers")</li>
            @*<li>Witaj @user.Name</li>*@
        
        
        
    }
</nav>

-->



@*

    @if (user != null)
    {
        <img src="Images/portret.png" class="img-responsive" style="height:40px;" alt="Profile picture">
        <p>Witaj @user.Name</p>

        using (Html.BeginForm("LogOut", "AppUser", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
        {
            @Html.AntiForgeryToken()
            <a href="javascript:document.getElementById('logoutForm').submit()">Log off</a>
        }
    }
    else
    {
        <ul class="nav navbar-nav navbar-right">
            <li>@Html.ActionLink("Zarejestruj", "Register", "AppUser", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
            <li>@Html.ActionLink("Zaloguj się", "Login", "AppUser", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
        </ul>
    }
*@